/*
 * generated by Xtext
 */
package org.gemoc.bcool.model.xtext;
/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BCOoLRuntimeModule extends org.gemoc.bcool.model.xtext.AbstractBCOoLRuntimeModule {

	//public Class<? extends XMemberFeatureCallImpl> xbaseCompiler{
	//	return TemplateCompiler.class;
	//}
	
	
	
//	@Override
//	public Class<? extends ITypeComputer> bindITypeComputer() {
//		return BCOoLTypeComputer.class;
//	}
	
//	@Override
//	public Class<? extends XbaseBatchScopeProvider> bindXbaseBatchScopeProvider() {
//		return BCOoLBatchScopeProvider.class;
//	}
//	
//	@Override
//	public Class<? extends IScopeProvider> bindIScopeProvider() {
//		return BCOoLScopeProvider.class;
//	}
	
	//@Override
	//public Class<? extends IGlobalScopeProvider> bindIGlobalScopeProvider() {
	//	return NullGlobalScopeProvider.class;
	//}
	
}

