/*
 * generated by Xtext
 */
package org.gemoc.bcool.model.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class BCOoLUiModule extends org.gemoc.bcool.model.xtext.ui.AbstractBCOoLUiModule {
	public BCOoLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
