/*
 * generated by Xtext
 */
package org.gemoc.bflow.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class BFlowUiModule extends org.gemoc.bflow.ui.AbstractBFlowUiModule {
	public BFlowUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
