/*
* generated by Xtext
*/
package org.gemoc.bflow;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class BFlowStandaloneSetup extends BFlowStandaloneSetupGenerated{

	public static void doSetup() {
		new BFlowStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

