/*
 * generated by Xtext
 */
package org.gemoc.bcool.model.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.gemoc.bcool.model.xtext.ui.internal.BCOoLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class BCOoLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return BCOoLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return BCOoLActivator.getInstance().getInjector(BCOoLActivator.ORG_GEMOC_BCOOL_MODEL_XTEXT_BCOOL);
	}
	
}
