/*
 * generated by Xtext
 */
package org.gemoc.bcool.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class BCOoLLibUiModule extends org.gemoc.bcool.ui.AbstractBCOoLLibUiModule {
	public BCOoLLibUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
