/*
* generated by Xtext
*/
package org.gemoc.gel.parser.antlr;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.gemoc.gel.services.GELGrammarAccess;

import com.google.inject.Inject;

public class GELParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private GELGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.gemoc.gel.parser.antlr.internal.InternalGELParser createParser(XtextTokenStream stream) {
		return new org.gemoc.gel.parser.antlr.internal.InternalGELParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "DomainSpecificEventsSpecification";
	}
	
	public GELGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(GELGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
