/*
* generated by Xtext
*/
package org.gemoc.bcool.model.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class BCOoLAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/gemoc/bcool/model/xtext/parser/antlr/internal/InternalBCOoL.tokens");
	}
}
