/*
 * generated by Xtext
 */
package org.gemoc.bcool.model.xtext.ui.contentassist

import org.gemoc.bcool.model.xtext.ui.contentassist.AbstractBCOoLProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class BCOoLProposalProvider extends AbstractBCOoLProposalProvider {
}
