/*
 * generated by Xtext
 */
package org.gemoc.gel;

import org.eclipse.xtext.linking.ILinker;
import org.gemoc.gel.linking.GELLinker;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class GELRuntimeModule extends org.gemoc.gel.AbstractGELRuntimeModule {
	@Override
	public Class<? extends ILinker> bindILinker() {
		return GELLinker.class;
	}
	
	 
}
