/*
 * generated by Xtext
 */
package org.gemoc.gel;

/**
 * Initialization support for running Xtext languages without equinox extension
 * registry
 */
public class GELStandaloneSetup extends GELStandaloneSetupGenerated {

	public static void doSetup() {
		new GELStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
