/*
* generated by Xtext
*/
package org.gemoc.gel.ui.outline

import org.gemoc.gexpressions.xtext.ui.outline.GExpressionsOutlineTreeProvider

/**
 * Customization of the default outline structure.
 *
 * see http://www.eclipse.org/Xtext/documentation.html#outline
 */
class GELOutlineTreeProvider extends GExpressionsOutlineTreeProvider {
	
}
