/*
* generated by Xtext
*/
package org.gemoc.bcool.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class BCOoLLibAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/gemoc/bcool/parser/antlr/internal/InternalBCOoLLib.tokens");
	}
}
