/*
* generated by Xtext
*/
package org.gemoc.bcool.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.gemoc.bcool.services.BCOoLLibGrammarAccess;

public class BCOoLLibParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private BCOoLLibGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.gemoc.bcool.parser.antlr.internal.InternalBCOoLLibParser createParser(XtextTokenStream stream) {
		return new org.gemoc.bcool.parser.antlr.internal.InternalBCOoLLibParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "BCoolLibrary";
	}
	
	public BCOoLLibGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(BCOoLLibGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
